series: GLFW Graphics
title: Instancing Tutorial
author:
  name: IGME-RIT
  email:
  github: igme-rit
description: This demo introduces the concept of instanced rendering.
language: C++
tags:
  - Graphics
extra_resources:
connections:
  - series: GLFW Graphics
    title: Multi-Object Multi-Buffer
